package weekSix;

public class MarylandResident {
    private String name;
    String zipCode;
    String city;
    String county;
    boolean found;
    //each row 0 = zipCode, 1 = city,  2 = State, 3 = county 
    private static String [][] MarylandZipCodeArray = {
            { "20601", "Waldorf", "MD", "Charles County" }, 
            { "20602", "Waldorf", "MD", "Charles County" }, 
            { "20603", "Waldorf", "MD", "Charles County" }, 
            { "20604", "Waldorf", "MD", "Charles County" }, 
            { "20606", "Abell", "MD", "St Mary's County" }, 
            { "20607", "Accokeek", "MD", "Prince George's County" }, 
            { "20608", "Aquasco", "MD", "Prince George's County" }, 
            { "20609", "Avenue", "MD", "St Mary's County" }, 
            { "20610", "Barstow", "MD", "Calvert County" }, 
            { "20611", "Bel Alton", "MD", "Charles County" }, 
            { "20612", "Benedict", "MD", "Charles County" }, 
            { "20613", "Brandywine", "MD", "Prince George's County" }, 
            { "20615", "Broomes Island", "MD", "Calvert County" }, 
            { "20616", "Bryans Road", "MD", "Charles County" }, 
            { "20617", "Bryantown", "MD", "Charles County" }, 
            { "20618", "Bushwood", "MD", "St Mary's County" }, 
            { "20619", "California", "MD", "St Mary's County" }, 
            { "20620", "Callaway", "MD", "St Mary's County" }, 
            { "20621", "Chaptico", "MD", "St Mary's County" }, 
            { "20622", "Charlotte Hall", "MD", "Charles County" }, 
            { "20623", "Cheltenham", "MD", "Prince George's County" }, 
            { "20624", "Clements", "MD", "St Mary's County" }, 
            { "20625", "Cobb Island", "MD", "Charles County" }, 
            { "20626", "Coltons Point", "MD", "St Mary's County" }, 
            { "20627", "Compton", "MD", "St. Mary's County" }, 
            { "20628", "Dameron", "MD", "St Mary's County" }, 
            { "20629", "Dowell", "MD", "Calvert County" }, 
            { "20630", "Drayden", "MD", "St Mary's County" }, 
            { "20632", "Faulkner", "MD", "Charles County" }, 
            { "20634", "Great Mills", "MD", "St Mary's County" }, 
            { "20635", "Helen", "MD", "St Mary's County" }, 
            { "20636", "Hollywood", "MD", "St Mary's County" }, 
            { "20637", "Hughesville", "MD", "Charles County" }, 
            { "20639", "Huntingtown", "MD", "Calvert County" }, 
            { "20640", "Indian Head", "MD", "Charles County" }, 
            { "20643", "Ironsides", "MD", "Charles County" }, 
            { "20645", "Issue", "MD", "Charles County" }, 
            { "20646", "La Plata", "MD", "Charles County" }, 
            { "20650", "Leonardtown", "MD", "St Mary's County" }, 
            { "20653", "Lexington Park", "MD", "St Mary's County" }, 
            { "20656", "Loveville", "MD", "St. Mary's County" }, 
            { "20657", "Lusby", "MD", "Calvert County" }, 
            { "20658", "Marbury", "MD", "Charles County" }, 
            { "20659", "Mechanicsville", "MD", "St Mary's County" }, 
            { "20660", "Morganza", "MD", "St Mary's County" }, 
            { "20661", "Mount Victoria", "MD", "Charles County" }, 
            { "20662", "Nanjemoy", "MD", "Charles County" }, 
            { "20664", "Newburg", "MD", "Charles County" }, 
            { "20667", "Park Hall", "MD", "St Mary's County" }, 
            { "20670", "Patuxent River", "MD", "St Mary's County" }, 
            { "20674", "Piney Point", "MD", "St Mary's County" }, 
            { "20675", "Pomfret", "MD", "Charles County" }, 
            { "20676", "Port Republic", "MD", "Calvert County" }, 
            { "20677", "Port Tobacco", "MD", "Charles County" }, 
            { "20678", "Prince Frederick", "MD", "Calvert County" }, 
            { "20680", "Ridge", "MD", "St Mary's County" }, 
            { "20682", "Rock Point", "MD", "Charles County" }, 
            { "20684", "Saint Inigoes", "MD", "St Mary's County" }, 
            { "20685", "Saint Leonard", "MD", "Calvert County" }, 
            { "20686", "Saint Marys City", "MD", "St. Mary's County" }, 
            { "20687", "Scotland", "MD", "St Mary's County" }, 
            { "20688", "Solomons", "MD", "Calvert County" }, 
            { "20689", "Sunderland", "MD", "Calvert County" }, 
            { "20690", "Tall Timbers", "MD", "St Mary's County" }, 
            { "20692", "Valley Lee", "MD", "St Mary's County" }, 
            { "20693", "Welcome", "MD", "Charles County" }, 
            { "20695", "White Plains", "MD", "Charles County" }, 
            { "20697", "Southern Md Facility", "MD", "Prince George's County" }, 
            { "20701", "Annapolis Junction", "MD", "Anne Arundel County" }, 
            { "20703", "Lanham", "MD", "Prince George's County" }, 
            { "20704", "Beltsville", "MD", "Prince George's County" }, 
            { "20705", "Beltsville", "MD", "Prince George's County" }, 
            { "20706", "Lanham", "MD", "Prince George's County" }, 
            { "20707", "Laurel", "MD", "Prince George's County" }, 
            { "20708", "Laurel", "MD", "Prince George's County" }, 
            { "20709", "Laurel", "MD", "Prince George's County" }, 
            { "20710", "Bladensburg", "MD", "Prince George's County" }, 
            { "20711", "Lothian", "MD", "Anne Arundel County" }, 
            { "20712", "Mount Rainier", "MD", "Prince George's County" }, 
            { "20714", "North Beach", "MD", "Calvert County" }, 
            { "20715", "Bowie", "MD", "Prince George's County" }, 
            { "20716", "Bowie", "MD", "Prince George's County" }, 
            { "20717", "Bowie", "MD", "Prince George's County" }, 
            { "20718", "Bowie", "MD", "Prince George's County" }, 
            { "20719", "Bowie", "MD", "Prince George's County" }, 
            { "20720", "Bowie", "MD", "Prince George's County" }, 
            { "20721", "Bowie", "MD", "Prince George's County" }, 
            { "20722", "Brentwood", "MD", "Prince George's County" }, 
            { "20723", "Laurel", "MD", "Howard County" }, 
            { "20724", "Laurel", "MD", "Anne Arundel County" }, 
            { "20725", "Laurel", "MD", "Prince George's County" }, 
            { "20726", "Laurel", "MD", "Prince George's County" }, 
            { "20731", "Capitol Heights", "MD", "Prince George's County" }, 
            { "20732", "Chesapeake Beach", "MD", "Calvert County" }, 
            { "20733", "Churchton", "MD", "Anne Arundel County" }, 
            { "20735", "Clinton", "MD", "Prince George's County" }, 
            { "20736", "Owings", "MD", "Calvert County" }, 
            { "20737", "Riverdale", "MD", "Prince George's County" }, 
            { "20738", "Riverdale", "MD", "Prince George's County" }, 
            { "20740", "College Park", "MD", "Prince George's County" }, 
            { "20741", "College Park", "MD", "Prince George's County" }, 
            { "20742", "College Park", "MD", "Prince George's County" }, 
            { "20743", "Capitol Heights", "MD", "Prince George's County" }, 
            { "20744", "Fort Washington", "MD", "Prince George's County" }, 
            { "20745", "Oxon Hill", "MD", "Prince George's County" }, 
            { "20746", "Suitland", "MD", "Prince George's County" }, 
            { "20747", "District Heights", "MD", "Prince George's County" }, 
            { "20748", "Temple Hills", "MD", "Prince George's County" }, 
            { "20749", "Fort Washington", "MD", "Prince George's County" }, 
            { "20750", "Oxon Hill", "MD", "Prince George's County" }, 
            { "20751", "Deale", "MD", "Anne Arundel County" }, 
            { "20752", "Suitland", "MD", "Prince George's County" }, 
            { "20753", "District Heights", "MD", "Prince George's County" }, 
            { "20754", "Dunkirk", "MD", "Calvert County" }, 
            { "20755", "Fort George G Meade", "MD", "Anne Arundel County" }, 
            { "20757", "Temple Hills", "MD", "Prince George's County" }, 
            { "20758", "Friendship", "MD", "Anne Arundel County" }, 
            { "20759", "Fulton", "MD", "Howard County" }, 
            { "20762", "Andrews Air Force Base", "MD", "Prince George's County" }, 
            { "20763", "Savage", "MD", "Howard County" }, 
            { "20764", "Shady Side", "MD", "Anne Arundel County" }, 
            { "20765", "Galesville", "MD", "Anne Arundel County" }, 
            { "20768", "Greenbelt", "MD", "Prince George's County" }, 
            { "20769", "Glenn Dale", "MD", "Prince George's County" }, 
            { "20770", "Greenbelt", "MD", "Prince George's County" }, 
            { "20771", "Greenbelt", "MD", "Prince George's County" }, 
            { "20772", "Upper Marlboro", "MD", "Prince George's County" }, 
            { "20773", "Upper Marlboro", "MD", "Prince George's County" }, 
            { "20774", "Upper Marlboro", "MD", "Prince George's County" }, 
            { "20775", "Upper Marlboro", "MD", "Prince George's County" }, 
            { "20776", "Harwood", "MD", "Anne Arundel County" }, 
            { "20777", "Highland", "MD", "Howard County" }, 
            { "20778", "West River", "MD", "Anne Arundel County" }, 
            { "20779", "Tracys Landing", "MD", "Anne Arundel County" }, 
            { "20781", "Hyattsville", "MD", "Prince George's County" }, 
            { "20782", "Hyattsville", "MD", "Prince George's County" }, 
            { "20783", "Hyattsville", "MD", "Prince George's County" }, 
            { "20784", "Hyattsville", "MD", "Prince George's County" }, 
            { "20785", "Hyattsville", "MD", "Prince George's County" }, 
            { "20787", "Hyattsville", "MD", "Prince George's County" }, 
            { "20788", "Hyattsville", "MD", "Prince George's County" }, 
            { "20790", "Capitol Heights", "MD", "Prince George's County" }, 
            { "20791", "Capitol Heights", "MD", "Prince George's County" }, 
            { "20792", "Upper Marlboro", "MD", "Prince George's County" }, 
            { "20794", "Jessup", "MD", "Howard County" }, 
            { "20797", "Southern Md Facility", "MD", "Prince George's County" }, 
            { "20799", "Capitol Heights", "MD", "Prince George's County" }, 
            { "20810", "Bethesda", "MD", "Montgomery County" }, 
            { "20811", "Bethesda", "MD", "Montgomery County" }, 
            { "20812", "Glen Echo", "MD", "Montgomery County" }, 
            { "20813", "Bethesda", "MD", "Montgomery County" }, 
            { "20814", "Bethesda", "MD", "Montgomery County" }, 
            { "20815", "Chevy Chase", "MD", "Montgomery County" }, 
            { "20816", "Bethesda", "MD", "Montgomery County" }, 
            { "20817", "Bethesda", "MD", "Montgomery County" }, 
            { "20818", "Cabin John", "MD", "Montgomery County" }, 
            { "20824", "Bethesda", "MD", "Montgomery County" }, 
            { "20825", "Chevy Chase", "MD", "Montgomery County" }, 
            { "20827", "Bethesda", "MD", "Montgomery County" }, 
            { "20830", "Olney", "MD", "Montgomery County" }, 
            { "20832", "Olney", "MD", "Montgomery County" }, 
            { "20833", "Brookeville", "MD", "Montgomery County" }, 
            { "20837", "Poolesville", "MD", "Montgomery County" }, 
            { "20838", "Barnesville", "MD", "Montgomery County" }, 
            { "20839", "Beallsville", "MD", "Montgomery County" }, 
            { "20841", "Boyds", "MD", "Montgomery County" }, 
            { "20842", "Dickerson", "MD", "Montgomery County" }, 
            { "20847", "Rockville", "MD", "Montgomery County" }, 
            { "20848", "Rockville", "MD", "Montgomery County" }, 
            { "20849", "Rockville", "MD", "Montgomery County" }, 
            { "20850", "Rockville", "MD", "Montgomery County" }, 
            { "20851", "Rockville", "MD", "Montgomery County" }, 
            { "20852", "Rockville", "MD", "Montgomery County" }, 
            { "20853", "Rockville", "MD", "Montgomery County" }, 
            { "20854", "Potomac", "MD", "Montgomery County" }, 
            { "20855", "Derwood", "MD", "Montgomery County" }, 
            { "20857", "Rockville", "MD", "Montgomery County" }, 
            { "20859", "Potomac", "MD", "Montgomery County" }, 
            { "20860", "Sandy Spring", "MD", "Montgomery County" }, 
            { "20861", "Ashton", "MD", "Montgomery County" }, 
            { "20862", "Brinklow", "MD", "Montgomery County" }, 
            { "20866", "Burtonsville", "MD", "Montgomery County" }, 
            { "20868", "Spencerville", "MD", "Montgomery County" }, 
            { "20871", "Clarksburg", "MD", "Montgomery County" }, 
            { "20872", "Damascus", "MD", "Montgomery County" }, 
            { "20874", "Germantown", "MD", "Montgomery County" }, 
            { "20875", "Germantown", "MD", "Montgomery County" }, 
            { "20876", "Germantown", "MD", "Montgomery County" }, 
            { "20877", "Gaithersburg", "MD", "Montgomery County" }, 
            { "20878", "Gaithersburg", "MD", "Montgomery County" }, 
            { "20879", "Gaithersburg", "MD", "Montgomery County" }, 
            { "20880", "Washington Grove", "MD", "Montgomery County" }, 
            { "20882", "Gaithersburg", "MD", "Montgomery County" }, 
            { "20883", "Gaithersburg", "MD", "Montgomery County" }, 
            { "20884", "Gaithersburg", "MD", "Montgomery County" }, 
            { "20885", "Gaithersburg", "MD", "Montgomery County" }, 
            { "20886", "Montgomery Village", "MD", "Montgomery County" }, 
            { "20889", "Bethesda", "MD", "Montgomery County" }, 
            { "20891", "Kensington", "MD", "Montgomery County" }, 
            { "20892", "Bethesda", "MD", "Montgomery County" }, 
            { "20894", "Bethesda", "MD", "Montgomery County" }, 
            { "20895", "Kensington", "MD", "Montgomery County" }, 
            { "20896", "Garrett Park", "MD", "Montgomery County" }, 
            { "20897", "Suburb Maryland Fac", "MD", "Montgomery County" }, 
            { "20898", "Gaithersburg", "MD", "Montgomery County" }, 
            { "20899", "Gaithersburg", "MD", "Montgomery County" }, 
            { "20901", "Silver Spring", "MD", "Montgomery County" }, 
            { "20902", "Silver Spring", "MD", "Montgomery County" }, 
            { "20903", "Silver Spring", "MD", "Montgomery County" }, 
            { "20904", "Silver Spring", "MD", "Montgomery County" }, 
            { "20905", "Silver Spring", "MD", "Montgomery County" }, 
            { "20906", "Silver Spring", "MD", "Montgomery County" }, 
            { "20907", "Silver Spring", "MD", "Montgomery County" }, 
            { "20908", "Silver Spring", "MD", "Montgomery County" }, 
            { "20910", "Silver Spring", "MD", "Montgomery County" }, 
            { "20911", "Silver Spring", "MD", "Montgomery County" }, 
            { "20912", "Takoma Park", "MD", "Montgomery County" }, 
            { "20913", "Takoma Park", "MD", "Montgomery County" }, 
            { "20914", "Silver Spring", "MD", "Montgomery County" }, 
            { "20915", "Silver Spring", "MD", "Montgomery County" }, 
            { "20916", "Silver Spring", "MD", "Montgomery County" }, 
            { "20918", "Silver Spring", "MD", "Montgomery County" }, 
            { "20993", "Silver Spring", "MD", "Montgomery County" }, 
            { "20997", "Silver Spring", "MD", "Montgomery County" }, 
            { "21001", "Aberdeen", "MD", "Harford County" }, 
            { "21005", "Aberdeen Proving Ground", "MD", "Harford County" }, 
            { "21009", "Abingdon", "MD", "Harford County" }, 
            { "21010", "Gunpowder", "MD", "Harford County" }, 
            { "21012", "Arnold", "MD", "Anne Arundel County" }, 
            { "21013", "Baldwin", "MD", "Baltimore County" }, 
            { "21014", "Bel Air", "MD", "Harford County" }, 
            { "21015", "Bel Air", "MD", "Harford County" }, 
            { "21017", "Belcamp", "MD", "Harford County" }, 
            { "21018", "Benson", "MD", "Harford County" }, 
            { "21020", "Boring", "MD", "Baltimore County" }, 
            { "21022", "Brooklandville", "MD", "Baltimore County" }, 
            { "21023", "Butler", "MD", "Baltimore County" }, 
            { "21027", "Chase", "MD", "Baltimore County" }, 
            { "21028", "Churchville", "MD", "Harford County" }, 
            { "21029", "Clarksville", "MD", "Howard County" }, 
            { "21030", "Cockeysville", "MD", "Baltimore County" }, 
            { "21031", "Hunt Valley", "MD", "Baltimore County" }, 
            { "21032", "Crownsville", "MD", "Anne Arundel County" }, 
            { "21034", "Darlington", "MD", "Harford County" }, 
            { "21035", "Davidsonville", "MD", "Anne Arundel County" }, 
            { "21036", "Dayton", "MD", "Howard County" }, 
            { "21037", "Edgewater", "MD", "Anne Arundel County" }, 
            { "21040", "Edgewood", "MD", "Harford County" }, 
            { "21041", "Ellicott City", "MD", "Howard County" }, 
            { "21042", "Ellicott City", "MD", "Howard County" }, 
            { "21043", "Ellicott City", "MD", "Howard County" }, 
            { "21044", "Columbia", "MD", "Howard County" }, 
            { "21045", "Columbia", "MD", "Howard County" }, 
            { "21046", "Columbia", "MD", "Howard County" }, 
            { "21047", "Fallston", "MD", "Harford County" }, 
            { "21048", "Finksburg", "MD", "Carroll County" }, 
            { "21050", "Forest Hill", "MD", "Harford County" }, 
            { "21051", "Fork", "MD", "Baltimore County" }, 
            { "21052", "Fort Howard", "MD", "Baltimore County" }, 
            { "21053", "Freeland", "MD", "Baltimore County" }, 
            { "21054", "Gambrills", "MD", "Anne Arundel County" }, 
            { "21056", "Gibson Island", "MD", "Anne Arundel County" }, 
            { "21057", "Glen Arm", "MD", "Baltimore County" }, 
            { "21060", "Glen Burnie", "MD", "Anne Arundel County" }, 
            { "21061", "Glen Burnie", "MD", "Anne Arundel County" }, 
            { "21062", "Glen Burnie", "MD", "Anne Arundel County" }, 
            { "21065", "Hunt Valley", "MD", "Baltimore County" }, 
            { "21071", "Glyndon", "MD", "Baltimore County" }, 
            { "21074", "Hampstead", "MD", "Carroll County" }, 
            { "21075", "Elkridge", "MD", "Howard County" }, 
            { "21076", "Hanover", "MD", "Anne Arundel County" }, 
            { "21077", "Harmans", "MD", "Anne Arundel County" }, 
            { "21078", "Havre De Grace", "MD", "Harford County" }, 
            { "21082", "Hydes", "MD", "Baltimore County" }, 
            { "21084", "Jarrettsville", "MD", "Harford County" }, 
            { "21085", "Joppa", "MD", "Harford County" }, 
            { "21087", "Kingsville", "MD", "Baltimore County" }, 
            { "21088", "Lineboro", "MD", "Carroll County" }, 
            { "21090", "Linthicum Heights", "MD", "Anne Arundel County" }, 
            { "21092", "Long Green", "MD", "Baltimore County" }, 
            { "21093", "Lutherville Timonium", "MD", "Baltimore County" }, 
            { "21094", "Lutherville Timonium", "MD", "Baltimore County" }, 
            { "21098", "Hanover", "MD", "Anne Arundel County" }, 
            { "21102", "Manchester", "MD", "Carroll County" }, 
            { "21104", "Marriottsville", "MD", "Howard County" }, 
            { "21105", "Maryland Line", "MD", "Baltimore County" }, 
            { "21106", "Mayo", "MD", "Anne Arundel County" }, 
            { "21108", "Millersville", "MD", "Anne Arundel County" }, 
            { "21111", "Monkton", "MD", "Baltimore County" }, 
            { "21113", "Odenton", "MD", "Anne Arundel County" }, 
            { "21114", "Crofton", "MD", "Anne Arundel County" }, 
            { "21117", "Owings Mills", "MD", "Baltimore County" }, 
            { "21120", "Parkton", "MD", "Baltimore County" }, 
            { "21122", "Pasadena", "MD", "Anne Arundel County" }, 
            { "21123", "Pasadena", "MD", "Anne Arundel County" }, 
            { "21128", "Perry Hall", "MD", "Baltimore County" }, 
            { "21130", "Perryman", "MD", "Harford County" }, 
            { "21131", "Phoenix", "MD", "Baltimore County" }, 
            { "21132", "Pylesville", "MD", "Harford County" }, 
            { "21133", "Randallstown", "MD", "Baltimore County" }, 
            { "21136", "Reisterstown", "MD", "Baltimore County" }, 
            { "21139", "Riderwood", "MD", "Baltimore County" }, 
            { "21140", "Riva", "MD", "Anne Arundel County" }, 
            { "21144", "Severn", "MD", "Anne Arundel County" }, 
            { "21146", "Severna Park", "MD", "Anne Arundel County" }, 
            { "21150", "Simpsonville", "MD", "Howard County" }, 
            { "21152", "Sparks Glencoe", "MD", "Baltimore County" }, 
            { "21153", "Stevenson", "MD", "Baltimore County" }, 
            { "21154", "Street", "MD", "Harford County" }, 
            { "21155", "Upperco", "MD", "Baltimore County" }, 
            { "21156", "Upper Falls", "MD", "Baltimore County" }, 
            { "21157", "Westminster", "MD", "Carroll County" }, 
            { "21158", "Westminster", "MD", "Carroll County" }, 
            { "21160", "Whiteford", "MD", "Harford County" }, 
            { "21161", "White Hall", "MD", "Baltimore County" }, 
            { "21162", "White Marsh", "MD", "Baltimore County" }, 
            { "21163", "Woodstock", "MD", "Howard County" }, 
            { "21201", "Baltimore", "MD", "Baltimore City" }, 
            { "21202", "Baltimore", "MD", "Baltimore City" }, 
            { "21203", "Baltimore", "MD", "Baltimore City" }, 
            { "21204", "Towson", "MD", "Baltimore County" }, 
            { "21205", "Baltimore", "MD", "Baltimore City" }, 
            { "21206", "Baltimore", "MD", "Baltimore City" }, 
            { "21207", "Gwynn Oak", "MD", "Baltimore County" }, 
            { "21208", "Pikesville", "MD", "Baltimore County" }, 
            { "21209", "Baltimore", "MD", "Baltimore City" }, 
            { "21210", "Baltimore", "MD", "Baltimore City" }, 
            { "21211", "Baltimore", "MD", "Baltimore City" }, 
            { "21212", "Baltimore", "MD", "Baltimore City" }, 
            { "21213", "Baltimore", "MD", "Baltimore City" }, 
            { "21214", "Baltimore", "MD", "Baltimore City" }, 
            { "21215", "Baltimore", "MD", "Baltimore City" }, 
            { "21216", "Baltimore", "MD", "Baltimore City" }, 
            { "21217", "Baltimore", "MD", "Baltimore City" }, 
            { "21218", "Baltimore", "MD", "Baltimore City" }, 
            { "21219", "Sparrows Point", "MD", "Baltimore County" }, 
            { "21220", "Middle River", "MD", "Baltimore County" }, 
            { "21221", "Essex", "MD", "Baltimore County" }, 
            { "21222", "Dundalk", "MD", "Baltimore County" }, 
            { "21223", "Baltimore", "MD", "Baltimore City" }, 
            { "21224", "Baltimore", "MD", "Baltimore City" }, 
            { "21225", "Brooklyn", "MD", "Anne Arundel County" }, 
            { "21226", "Curtis Bay", "MD", "Baltimore City" }, 
            { "21227", "Halethorpe", "MD", "Baltimore County" }, 
            { "21228", "Catonsville", "MD", "Baltimore County" }, 
            { "21229", "Baltimore", "MD", "Baltimore City" }, 
            { "21230", "Baltimore", "MD", "Baltimore City" }, 
            { "21231", "Baltimore", "MD", "Baltimore City" }, 
            { "21233", "Baltimore", "MD", "Baltimore City" }, 
            { "21234", "Parkville", "MD", "Baltimore County" }, 
            { "21235", "Baltimore", "MD", "Baltimore City" }, 
            { "21236", "Nottingham", "MD", "Baltimore County" }, 
            { "21237", "Rosedale", "MD", "Baltimore County" }, 
            { "21239", "Baltimore", "MD", "Baltimore City" }, 
            { "21240", "Baltimore", "MD", "Anne Arundel County" }, 
            { "21241", "Baltimore", "MD", "Baltimore City" }, 
            { "21244", "Windsor Mill", "MD", "Baltimore County" }, 
            { "21250", "Baltimore", "MD", "Baltimore County" }, 
            { "21251", "Baltimore", "MD", "Baltimore City" }, 
            { "21252", "Towson", "MD", "Baltimore County" }, 
            { "21260", "Baltimore", "MD", "Baltimore City" }, 
            { "21261", "Baltimore", "MD", "Baltimore City" }, 
            { "21263", "Baltimore", "MD", "Baltimore City" }, 
            { "21264", "Baltimore", "MD", "Baltimore City" }, 
            { "21265", "Baltimore", "MD", "Baltimore City" }, 
            { "21268", "Baltimore", "MD", "Baltimore City" }, 
            { "21270", "Baltimore", "MD", "Baltimore City" }, 
            { "21273", "Baltimore", "MD", "Baltimore City" }, 
            { "21274", "Baltimore", "MD", "Baltimore City" }, 
            { "21275", "Baltimore", "MD", "Baltimore City" }, 
            { "21278", "Baltimore", "MD", "Baltimore City" }, 
            { "21279", "Baltimore", "MD", "Baltimore City" }, 
            { "21280", "Baltimore", "MD", "Baltimore City" }, 
            { "21281", "Baltimore", "MD", "Baltimore City" }, 
            { "21282", "Baltimore", "MD", "Baltimore City" }, 
            { "21283", "Baltimore", "MD", "Baltimore City" }, 
            { "21284", "Baltimore", "MD", "Baltimore City" }, 
            { "21285", "Baltimore", "MD", "Baltimore City" }, 
            { "21286", "Towson", "MD", "Baltimore County" }, 
            { "21287", "Baltimore", "MD", "Baltimore City" }, 
            { "21288", "Baltimore", "MD", "Baltimore City" }, 
            { "21289", "Baltimore", "MD", "Baltimore City" }, 
            { "21290", "Baltimore", "MD", "Baltimore City" }, 
            { "21297", "Baltimore", "MD", "Baltimore City" }, 
            { "21298", "Baltimore", "MD", "Baltimore City" }, 
            { "21401", "Annapolis", "MD", "Anne Arundel County" }, 
            { "21402", "Annapolis", "MD", "Anne Arundel County" }, 
            { "21403", "Annapolis", "MD", "Anne Arundel County" }, 
            { "21404", "Annapolis", "MD", "Anne Arundel County" }, 
            { "21405", "Annapolis", "MD", "Anne Arundel County" }, 
            { "21409", "Annapolis", "MD", "Anne Arundel County" }, 
            { "21411", "Annapolis", "MD", "Anne Arundel County" }, 
            { "21412", "Annapolis", "MD", "Anne Arundel County" }, 
            { "21501", "Cumberland", "MD", "Allegany County" }, 
            { "21502", "Cumberland", "MD", "Allegany County" }, 
            { "21503", "Cumberland", "MD", "Allegany County" }, 
            { "21504", "Cumberland", "MD", "Allegany County" }, 
            { "21505", "Cumberland", "MD", "Allegany County" }, 
            { "21520", "Accident", "MD", "Garrett County" }, 
            { "21521", "Barton", "MD", "Allegany County" }, 
            { "21522", "Bittinger", "MD", "Garrett County" }, 
            { "21523", "Bloomington", "MD", "Garrett County" }, 
            { "21524", "Corriganville", "MD", "Allegany County" }, 
            { "21528", "Eckhart Mines", "MD", "Allegany County" }, 
            { "21529", "Ellerslie", "MD", "Allegany County" }, 
            { "21530", "Flintstone", "MD", "Allegany County" }, 
            { "21531", "Friendsville", "MD", "Garrett County" }, 
            { "21532", "Frostburg", "MD", "Allegany County" }, 
            { "21536", "Grantsville", "MD", "Garrett County" }, 
            { "21538", "Kitzmiller", "MD", "Garrett County" }, 
            { "21539", "Lonaconing", "MD", "Allegany County" }, 
            { "21540", "Luke", "MD", "Allegany County" }, 
            { "21541", "Mc Henry", "MD", "Garrett County" }, 
            { "21542", "Midland", "MD", "Allegany County" }, 
            { "21543", "Midlothian", "MD", "Allegany County" }, 
            { "21545", "Mount Savage", "MD", "Allegany County" }, 
            { "21550", "Oakland", "MD", "Garrett County" }, 
            { "21555", "Oldtown", "MD", "Allegany County" }, 
            { "21556", "Pinto", "MD", "Allegany County" }, 
            { "21557", "Rawlings", "MD", "Allegany County" }, 
            { "21560", "Spring Gap", "MD", "Mineral County" }, 
            { "21561", "Swanton", "MD", "Garrett County" }, 
            { "21562", "Westernport", "MD", "Allegany County" }, 
            { "21601", "Easton", "MD", "Talbot County" }, 
            { "21606", "Easton", "MD", "Talbot County" }, 
            { "21607", "Barclay", "MD", "Queen Anne's County" }, 
            { "21609", "Bethlehem", "MD", "Caroline County" }, 
            { "21610", "Betterton", "MD", "Kent County" }, 
            { "21612", "Bozman", "MD", "Talbot County" }, 
            { "21613", "Cambridge", "MD", "Dorchester County" }, 
            { "21617", "Centreville", "MD", "Queen Anne's County" }, 
            { "21619", "Chester", "MD", "Queen Anne's County" }, 
            { "21620", "Chestertown", "MD", "Kent County" }, 
            { "21622", "Church Creek", "MD", "Dorchester County" }, 
            { "21623", "Church Hill", "MD", "Queen Anne's County" }, 
            { "21624", "Claiborne", "MD", "Talbot County" }, 
            { "21625", "Cordova", "MD", "Talbot County" }, 
            { "21626", "Crapo", "MD", "Dorchester County" }, 
            { "21627", "Crocheron", "MD", "Dorchester County" }, 
            { "21628", "Crumpton", "MD", "Queen Anne's County" }, 
            { "21629", "Denton", "MD", "Caroline County" }, 
            { "21631", "East New Market", "MD", "Dorchester County" }, 
            { "21632", "Federalsburg", "MD", "Caroline County" }, 
            { "21634", "Fishing Creek", "MD", "Dorchester County" }, 
            { "21635", "Galena", "MD", "Kent County" }, 
            { "21636", "Goldsboro", "MD", "Caroline County" }, 
            { "21638", "Grasonville", "MD", "Queen Anne's County" }, 
            { "21639", "Greensboro", "MD", "Caroline County" }, 
            { "21640", "Henderson", "MD", "Caroline County" }, 
            { "21641", "Hillsboro", "MD", "Caroline County" }, 
            { "21643", "Hurlock", "MD", "Dorchester County" }, 
            { "21644", "Ingleside", "MD", "Queen Anne's County" }, 
            { "21645", "Kennedyville", "MD", "Kent County" }, 
            { "21647", "Mcdaniel", "MD", "Talbot County" }, 
            { "21648", "Madison", "MD", "Dorchester County" }, 
            { "21649", "Marydel", "MD", "Caroline County" }, 
            { "21650", "Massey", "MD", "Kent County" }, 
            { "21651", "Millington", "MD", "Queen Anne's County" }, 
            { "21652", "Neavitt", "MD", "Talbot County" }, 
            { "21653", "Newcomb", "MD", "Talbot County" }, 
            { "21654", "Oxford", "MD", "Talbot County" }, 
            { "21655", "Preston", "MD", "Caroline County" }, 
            { "21656", "Price", "MD", "Queen Anne's County" }, 
            { "21657", "Queen Anne", "MD", "Queen Anne's County" }, 
            { "21658", "Queenstown", "MD", "Queen Anne's County" }, 
            { "21659", "Rhodesdale", "MD", "Dorchester County" }, 
            { "21660", "Ridgely", "MD", "Caroline County" }, 
            { "21661", "Rock Hall", "MD", "Kent County" }, 
            { "21662", "Royal Oak", "MD", "Talbot County" }, 
            { "21663", "Saint Michaels", "MD", "Talbot County" }, 
            { "21664", "Secretary", "MD", "Dorchester County" }, 
            { "21665", "Sherwood", "MD", "Talbot County" }, 
            { "21666", "Stevensville", "MD", "Queen Anne's County" }, 
            { "21667", "Still Pond", "MD", "Kent County" }, 
            { "21668", "Sudlersville", "MD", "Queen Anne's County" }, 
            { "21669", "Taylors Island", "MD", "Dorchester County" }, 
            { "21670", "Templeville", "MD", "Caroline County" }, 
            { "21671", "Tilghman", "MD", "Talbot County" }, 
            { "21672", "Toddville", "MD", "Dorchester County" }, 
            { "21673", "Trappe", "MD", "Talbot County" }, 
            { "21675", "Wingate", "MD", "Dorchester County" }, 
            { "21676", "Wittman", "MD", "Talbot County" }, 
            { "21677", "Woolford", "MD", "Dorchester County" }, 
            { "21678", "Worton", "MD", "Kent County" }, 
            { "21679", "Wye Mills", "MD", "Talbot County" }, 
            { "21681", "Ridgely", "MD", "Caroline County" }, 
            { "21682", "Ridgely", "MD", "Caroline County" }, 
            { "21683", "Ridgely", "MD", "Caroline County" }, 
            { "21684", "Ridgely", "MD", "Caroline County" }, 
            { "21685", "Ridgely", "MD", "Caroline County" }, 
            { "21686", "Ridgely", "MD", "Caroline County" }, 
            { "21687", "Ridgely", "MD", "Caroline County" }, 
            { "21688", "Ridgely", "MD", "Caroline County" }, 
            { "21690", "Chestertown", "MD", "Kent County" }, 
            { "21701", "Frederick", "MD", "Frederick County" }, 
            { "21702", "Frederick", "MD", "Frederick County" }, 
            { "21703", "Frederick", "MD", "Frederick County" }, 
            { "21704", "Frederick", "MD", "Frederick County" }, 
            { "21705", "Frederick", "MD", "Frederick County" }, 
            { "21709", "Frederick", "MD", "Frederick County" }, 
            { "21710", "Adamstown", "MD", "Frederick County" }, 
            { "21711", "Big Pool", "MD", "Washington County" }, 
            { "21713", "Boonsboro", "MD", "Washington County" }, 
            { "21714", "Braddock Heights", "MD", "Frederick County" }, 
            { "21715", "Brownsville", "MD", "Washington County" }, 
            { "21716", "Brunswick", "MD", "Frederick County" }, 
            { "21717", "Buckeystown", "MD", "Frederick County" }, 
            { "21718", "Burkittsville", "MD", "Frederick County" }, 
            { "21719", "Cascade", "MD", "Washington County" }, 
            { "21720", "Cavetown", "MD", "Washington County" }, 
            { "21721", "Chewsville", "MD", "Washington County" }, 
            { "21722", "Clear Spring", "MD", "Washington County" }, 
            { "21723", "Cooksville", "MD", "Howard County" }, 
            { "21727", "Emmitsburg", "MD", "Frederick County" }, 
            { "21733", "Fairplay", "MD", "Washington County" }, 
            { "21734", "Funkstown", "MD", "Washington County" }, 
            { "21737", "Glenelg", "MD", "Howard County" }, 
            { "21738", "Glenwood", "MD", "Howard County" }, 
            { "21740", "Hagerstown", "MD", "Washington County" }, 
            { "21741", "Hagerstown", "MD", "Washington County" }, 
            { "21742", "Hagerstown", "MD", "Washington County" }, 
            { "21746", "Hagerstown", "MD", "Washington County" }, 
            { "21747", "Hagerstown", "MD", "Washington County" }, 
            { "21748", "Hagerstown", "MD", "Washington County" }, 
            { "21749", "Hagerstown", "MD", "Washington County" }, 
            { "21750", "Hancock", "MD", "Washington County" }, 
            { "21754", "Ijamsville", "MD", "Frederick County" }, 
            { "21755", "Jefferson", "MD", "Frederick County" }, 
            { "21756", "Keedysville", "MD", "Washington County" }, 
            { "21757", "Keymar", "MD", "Frederick County" }, 
            { "21758", "Knoxville", "MD", "Frederick County" }, 
            { "21759", "Ladiesburg", "MD", "Frederick County" }, 
            { "21762", "Libertytown", "MD", "Frederick County" }, 
            { "21765", "Lisbon", "MD", "Howard County" }, 
            { "21766", "Little Orleans", "MD", "Allegany County" }, 
            { "21767", "Maugansville", "MD", "Washington County" }, 
            { "21769", "Middletown", "MD", "Frederick County" }, 
            { "21770", "Monrovia", "MD", "Frederick County" }, 
            { "21771", "Mount Airy", "MD", "Carroll County" }, 
            { "21773", "Myersville", "MD", "Frederick County" }, 
            { "21774", "New Market", "MD", "Frederick County" }, 
            { "21775", "New Midway", "MD", "Frederick County" }, 
            { "21776", "New Windsor", "MD", "Carroll County" }, 
            { "21777", "Point Of Rocks", "MD", "Frederick County" }, 
            { "21778", "Rocky Ridge", "MD", "Frederick County" }, 
            { "21779", "Rohrersville", "MD", "Washington County" }, 
            { "21780", "Sabillasville", "MD", "Frederick County" }, 
            { "21781", "Saint James", "MD", "Washington County" }, 
            { "21782", "Sharpsburg", "MD", "Washington County" }, 
            { "21783", "Smithsburg", "MD", "Washington County" }, 
            { "21784", "Sykesville", "MD", "Carroll County" }, 
            { "21787", "Taneytown", "MD", "Carroll County" }, 
            { "21788", "Thurmont", "MD", "Frederick County" }, 
            { "21790", "Tuscarora", "MD", "Frederick County" }, 
            { "21791", "Union Bridge", "MD", "Frederick County" }, 
            { "21792", "Unionville", "MD", "Frederick County" }, 
            { "21793", "Walkersville", "MD", "Frederick County" }, 
            { "21794", "West Friendship", "MD", "Howard County" }, 
            { "21795", "Williamsport", "MD", "Washington County" }, 
            { "21797", "Woodbine", "MD", "Howard County" }, 
            { "21798", "Woodsboro", "MD", "Frederick County" }, 
            { "21801", "Salisbury", "MD", "Wicomico County" }, 
            { "21802", "Salisbury", "MD", "Wicomico County" }, 
            { "21803", "Salisbury", "MD", "Wicomico County" }, 
            { "21804", "Salisbury", "MD", "Wicomico County" }, 
            { "21810", "Allen", "MD", "Somerset County" }, 
            { "21811", "Berlin", "MD", "Worcester County" }, 
            { "21813", "Bishopville", "MD", "Worcester County" }, 
            { "21814", "Bivalve", "MD", "Wicomico County" }, 
            { "21817", "Crisfield", "MD", "Somerset County" }, 
            { "21821", "Deal Island", "MD", "Somerset County" }, 
            { "21822", "Eden", "MD", "Somerset County" }, 
            { "21824", "Ewell", "MD", "Somerset County" }, 
            { "21826", "Fruitland", "MD", "Wicomico County" }, 
            { "21829", "Girdletree", "MD", "Worcester County" }, 
            { "21830", "Hebron", "MD", "Wicomico County" }, 
            { "21835", "Linkwood", "MD", "Dorchester County" }, 
            { "21836", "Manokin", "MD", "Somerset County" }, 
            { "21837", "Mardela Springs", "MD", "Wicomico County" }, 
            { "21838", "Marion Station", "MD", "Somerset County" }, 
            { "21840", "Nanticoke", "MD", "Wicomico County" }, 
            { "21841", "Newark", "MD", "Worcester County" }, 
            { "21842", "Ocean City", "MD", "Worcester County" }, 
            { "21843", "Ocean City", "MD", "Worcester County" }, 
            { "21849", "Parsonsburg", "MD", "Wicomico County" }, 
            { "21850", "Pittsville", "MD", "Wicomico County" }, 
            { "21851", "Pocomoke City", "MD", "Worcester County" }, 
            { "21852", "Powellville", "MD", "Wicomico County" }, 
            { "21853", "Princess Anne", "MD", "Somerset County" }, 
            { "21856", "Quantico", "MD", "Wicomico County" }, 
            { "21857", "Rehobeth", "MD", "Somerset County" }, 
            { "21861", "Sharptown", "MD", "Wicomico County" }, 
            { "21862", "Showell", "MD", "Worcester County" }, 
            { "21863", "Snow Hill", "MD", "Worcester County" }, 
            { "21864", "Stockton", "MD", "Worcester County" }, 
            { "21865", "Tyaskin", "MD", "Wicomico County" }, 
            { "21866", "Tylerton", "MD", "Somerset County" }, 
            { "21867", "Upper Fairmount", "MD", "Somerset County" }, 
            { "21869", "Vienna", "MD", "Dorchester County" }, 
            { "21871", "Westover", "MD", "Somerset County" }, 
            { "21872", "Whaleyville", "MD", "Worcester County" }, 
            { "21874", "Willards", "MD", "Wicomico County" }, 
            { "21875", "Delmar", "MD", "Wicomico County" }, 
            { "21890", "Westover", "MD", "Somerset County" }, 
            { "21901", "North East", "MD", "Cecil County" }, 
            { "21902", "Perry Point", "MD", "Cecil County" }, 
            { "21903", "Perryville", "MD", "Cecil County" }, 
            { "21904", "Port Deposit", "MD", "Cecil County" }, 
            { "21911", "Rising Sun", "MD", "Cecil County" }, 
            { "21912", "Warwick", "MD", "Cecil County" }, 
            { "21913", "Cecilton", "MD", "Cecil County" }, 
            { "21914", "Charlestown", "MD", "Cecil County" }, 
            { "21915", "Chesapeake City", "MD", "Cecil County" }, 
            { "21916", "Childs", "MD", "Cecil County" }, 
            { "21917", "Colora", "MD", "Cecil County" }, 
            { "21918", "Conowingo", "MD", "Cecil County" }, 
            { "21919", "Earleville", "MD", "Cecil County" }, 
            { "21920", "Elk Mills", "MD", "Cecil County" }, 
            { "21921", "Elkton", "MD", "Cecil County" }, 
            { "21922", "Elkton", "MD", "Cecil County" }, 
            { "21930", "Georgetown", "MD", "Cecil County" } 
        };

    //Constructor
    public MarylandResident (String zip, String na) {
        name = na;
        zipCode = zip;
        
        for(int i = 0; i < MarylandZipCodeArray.length; i++){ 
            //for(int j = 0; j < MarylandZipCodeArray[j].length; j++) { is this even needed?
                if(zip.equals(MarylandZipCodeArray[i][0])){
                    city = MarylandZipCodeArray[i][1];
                    county = MarylandZipCodeArray[i][3];
                    found = true;

                    }//End if
                }//End for loop
        //}//End second for loop... not needed for this i don't think??
        
    } //End Constructor
    
    
    //Method
    public boolean isFound() {
        return found;  
    }
    //Method
    public String Show1() {
        return name + city + county;  
    }
    //Method toString
    public String toString() {
        return name + " is from " + city + " which is a city within " + county;  
    }
/*
    //Method
    public String Show1() {
        return "Zips" + Arrays.deepToString(MarylandZipCodeArray) +"\n";  

    }
*/
}
